### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by Lving** [nothingyang/RiskModeler#2]
很棒的工作！
建议添加一个README的 markdown 文件，这样就更直观的了解到这个项目的相关内容和使用方法。

**Comment by nothingyang** [comment]
> 很棒的工作！
> 建议添加一个README的 markdown 文件，这样就更直观的了解到这个项目的相关内容和使用方法。

谢谢  我已经加上了  如果想更多信息可以关注公众号 人工智障风控
